# -*- coding: utf-8 -*-
"""Untitled42.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wQgaKyyjuvzy5PTXtvavbhKR4wJ-IalG
"""

# Recipe Parser - Level-1
!pip install recipe-scrapers

from recipe_scrapers import scrape_me


print("Welcome to The Interactive Cookbook. Provide a valid Allrecipes.com url/"
      "of recipe of your choice or type 'exit' to cancel. ")
req_url = (input("Enter recipe URL : "))

scraper = scrape_me(req_url)

#print(scraper.ingredients())
print(scraper.instructions())

from nltk import tokenize

import nltk

nltk.download('punkt')

q=scraper.instructions()

m=tokenize.sent_tokenize(q)

print(m)

